# Generated by Django 4.1.4 on 2023-02-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('telegram_id', models.IntegerField(unique=True)),
                ('language', models.CharField(default='uz', max_length=5)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
